# Generated by Django 5.0.7 on 2024-08-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_product_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": (["name", "category", "purchase_price"],),
                "permissions": [
                    ("can_edit_product", "Can edit product"),
                    ("can_edit_description", "Can edit description"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
