# Generated by Django 5.0.7 on 2024-08-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="version_number",
            field=models.FloatField(verbose_name="Номер версии"),
        ),
    ]
